### ISSUE TITLE
Утечка памяти

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#154]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on March 28, 2011 03:41:51_

В текущей гит версии версии пару раз наблюдал утечку памяти.
Оба раза программа была запущенна довольно долгое время, но проявлялось это лишь после выходных.
Так, айскальт запущен у меня на рабочем компе. Приходя в понедельник обнаруживал такое (см. скриншот)

Первый раз когда такое произошло у меня шара была пустая. Второй раз - нет.
Насчет активных поисков ничего сказать не могу. Постоянно в личку флудит хаб-бот.
Гит сборка где-то от 20ого числа.

**Attachment:** [снимок5.png](http://code.google.com/p/eiskaltdc/issues/detail?id=1027)

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1027_

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 06, 2011 23:08:56_

Вот еще один вопиющий случай.
При этом здесь видно, что память утекает не по мегабайту в час, а по десяткам в минуту.

К сожалению на тыканье в трей айскальт никак не реагировал.

**Attachment:** [снимок7.png](http://code.google.com/p/eiskaltdc/issues/detail?id=1027#hc1)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 07, 2011 00:13:36_

Сейчас такое поведение идет буквально сразу при запуске клиента.
Полная загрузка одного ядра и постоянное поедание памяти.

При попытке закрыть хаб:
(gdb) bt
\#0  0x0000000000000000 in ?? ()
\#1  0x000000000055864c in HubFrame::addPM (this=0x1348540, cid=..., output=..., keepfocus=true) at /usr/src/debug/eiskaltdcpp/eiskaltdcpp-qt/src/HubFrame.cpp:1894
\#2  0x000000000055c966 in HubFrame::newPm (this=0x1348540, map=<value optimized out>) at /usr/src/debug/eiskaltdcpp/eiskaltdcpp-qt/src/HubFrame.cpp:2353
\#3  0x00000000004ae599 in HubFrame::qt_metacall (this=0x1348540, _c=QMetaObject::InvokeMetaMethod, _id=67, _a=0x7fffe488bff0) at /usr/src/debug/eiskaltdcpp/eiskaltdcpp-qt/src/moc_HubFrame.cxx:252
\#4  0x00007ffff5c37a6a in QObject::event (this=0x1348540, e=<value optimized out>) at kernel/qobject.cpp:1211
\#5  0x00007ffff6950edd in QWidget::event(QEvent*) () from /usr/lib64/libQtGui.so.4
\#6  0x00007ffff68ffd14 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
\#7  0x00007ffff690822a in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQtGui.so.4
\#8  0x00007ffff5c23bfc in QCoreApplication::notifyInternal (this=0x7fffffffdb20, receiver=0x1348540, event=0x7fffe49c4920) at kernel/qcoreapplication.cpp:732
\#9  0x00007ffff5c273f5 in sendEvent (receiver=0x0, event_type=0, data=0xae1250) at kernel/qcoreapplication.h:215
\#10 QCoreApplicationPrivate::sendPostedEvents (receiver=0x0, event_type=0, data=0xae1250) at kernel/qcoreapplication.cpp:1373
\#11 0x00007ffff5c4e783 in sendPostedEvents (s=<value optimized out>) at kernel/qcoreapplication.h:220
\#12 postEventSourceDispatch (s=<value optimized out>) at kernel/qeventdispatcher_glib.cpp:277
\#13 0x00007ffff3b8dbd3 in g_main_context_dispatch () from /lib64/libglib-2.0.so.0
\#14 0x00007ffff3b8e3b0 in ?? () from /lib64/libglib-2.0.so.0
\#15 0x00007ffff3b8e650 in g_main_context_iteration () from /lib64/libglib-2.0.so.0
\#16 0x00007ffff5c4e91f in QEventDispatcherGlib::processEvents (this=0xae65e0, flags=<value optimized out>) at kernel/qeventdispatcher_glib.cpp:422
\#17 0x00007ffff69a4d8e in ?? () from /usr/lib64/libQtGui.so.4
\#18 0x00007ffff5c23052 in QEventLoop::processEvents (this=<value optimized out>, flags=...) at kernel/qeventloop.cpp:149
\#19 0x00007ffff5c23265 in QEventLoop::exec (this=0x7fffffffdad0, flags=...) at kernel/qeventloop.cpp:201
\#20 0x00007ffff5c276ab in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1009
\#21 0x000000000049e22d in main (argc=<value optimized out>, argv=<value optimized out>) at /usr/src/debug/eiskaltdcpp/eiskaltdcpp-qt/src/main.cpp:161


Оказалось все из-за постоянного флуда в ПМ. Десятки сообщений в секунду от операторского бота.

**Attachment:** [valgrind.log](http://code.google.com/p/eiskaltdc/issues/detail?id=1027#hc2)

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 07, 2011 00:15:23_

valgrind в этом плане оказался довольно бесполезен, так как из-за жуткого замедления работы программы постоянно рвалось соединение с хабом.

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 07, 2011 00:34:49_

Сотни сообщений, если быть точнее:
vovochka@vocomp:~/.config/eiskaltdc++/Logs> cat 2011-04-07\ chat\ with\ Оп\ \(64UC5BTCSBRIP2FUIQS4WGCLUIO7JBN7ZGZ24GI\).log | grep sharf | grep 17\:15\:54 | wc -l
419

**Comment by dhamp** [comment]
_From [vasily.n.k@eml.ru](https://code.google.com/u/vasily.n.k@eml.ru/) on April 09, 2011 02:50:48_

\>Сотни сообщений, 
Ну тогда понятно откуда утечки памяти, да это и не утечки, просто надо чат периодически очищать от сообщений или вообще выключить.
Странно, что не срабатывает обрезание по числу сообщений, может они такие длинные, что память кончается раньше, чем начинают отбрасываться.
Возможно стоит уменьшить в настройках GUI/chat(ext)/Maximum paragraphs.

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 10, 2011 23:44:49_

\> Возможно стоит уменьшить в настройках GUI/chat(ext)/Maximum paragraphs.
Если и так, то эта опция не применима к "личным сообщениям"

**Comment by dhamp** [comment]
_From [dein.neg...@gmail.com](https://code.google.com/u/106623909778569461799/) on April 11, 2011 02:41:32_

Vovochka,
Пару дней назад это было исправлено, теперь на личку это ограничение так же действует. Обновитесь.

**Comment by dhamp** [comment]
_From [Vovochka13](https://code.google.com/u/Vovochka13/) on April 14, 2011 19:15:26_

Несмотря на то, что ограничения теперь и впрямь распространяются на ЛС, от потребления памяти в пару гигов это не спасло.
