### ISSUE TITLE
Падения eiskaltdcpp-qt

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#162]
_From [unikum...@gmail.com](https://code.google.com/u/114963251942515168095/) on May 02, 2011 17:43:00_

What steps will reproduce the problem? 1. Запуск eiskaltdcpp-qt What is the expected output? What do you see instead? $ eiskaltdcpp-qt 
Signal handlers installed.
Loading: Хеш базы данных
Loading: Расшаренные файлы
Loading: Очередь
Loading: Пользователи
Загружены иконки для списка пользователей
Загружены иконки программы
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Аварийный останов What version of the product are you using? On what operating system? eiskaltdcpp-qt-2.2.2-1 Archlinux i686. Please provide any additional information below.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1063_

**Comment by dhamp** [comment]
_From [vasily.n.k@eml.ru](https://code.google.com/u/vasily.n.k@eml.ru/) on May 02, 2011 06:48:57_

std::bad_alloc означает, что недостаточно памяти при выделении оператором new.
Возникает вопрос: а памяти-то достаточно? может своп включить уже ))

**Comment by dhamp** [comment]
_From [unikum1...@gmail.com](https://code.google.com/u/108112664995663183860/) on May 02, 2011 07:02:14_

Памяти 4 Гб. Свап 2 Гб с небольшим.

**Comment by dhamp** [comment]
_From [vasily.n.k@eml.ru](https://code.google.com/u/vasily.n.k@eml.ru/) on May 02, 2011 07:36:26_

\>Возникает вопрос: а памяти-то достаточно?
имеется ввиду свободной памяти.
хотя может где-то в логике программы касяк, что есть попытка выделить 100500 мегов.
нужен подробный бэктрэйс.
попробуй https://code.google.com/p/eiskaltdc/wiki/issue_hints_ru

**Comment by dhamp** [comment]
_From [vasily.n.k@eml.ru](https://code.google.com/u/vasily.n.k@eml.ru/) on May 02, 2011 07:45:21_

Кстати что выдает команда free ?
И сколько хабов подключено, размер шары...
Вообщем надо много информации помимо слов "Падения eiskaltdcpp-qt".

**Comment by dhamp** [comment]
_From [unikum...@gmail.com](https://code.google.com/u/114963251942515168095/) on May 02, 2011 08:02:42_

free
             total       used       free     shared    buffers     cached
Mem:       3601520    3031180     570340          0      51260    1417252
-/+ buffers/cache:    1562668    2038852
Swap:      2200868          0    2200868

Поодключено 14 хабов. Шара: 690 Гб. Скорость: 10-100 м/бит.
Похоже падает при скачивании файла у большого количества юзеров, или при скачивании большого количество файл-листов.

(gdb) bt full
\#0  0xb7fff424 in __kernel_vsyscall ()
No symbol table info available.
\#1  0x450f6bbf in raise () from /lib/libc.so.6
No symbol table info available.
\#2  0x450f8545 in abort () from /lib/libc.so.6
No symbol table info available.
\#3  0x45379a77 in __gnu_cxx::__verbose_terminate_handler() () from /usr/lib/libstdc++.so.6
No symbol table info available.
\#4  0x45377833 in ?? () from /usr/lib/libstdc++.so.6
No symbol table info available.
\#5  0x4537786f in std::terminate() () from /usr/lib/libstdc++.so.6
No symbol table info available.
\#6  0x45377883 in ?? () from /usr/lib/libstdc++.so.6
No symbol table info available.
\#7  0x45377381 in __cxa_call_unexpected () from /usr/lib/libstdc++.so.6
No symbol table info available.
\#8  0x081fd32a in HubFrame::on(dcpp::ClientListener::X<3>, dcpp::Client*, dcpp::OnlineUser const&) ()
No symbol table info available.
\#9  0xb7ea3099 in void dcpp::Speaker<dcpp::ClientListener>::fire<dcpp::ClientListener::X<3>, dcpp::NmdcHub*, dcpp::OnlineUser>(dcpp::ClientListener::X<3>, dcpp::NmdcHub* const&, dcpp::OnlineUser const&) () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#10 0xb7e9e3eb in dcpp::NmdcHub::onLine(std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#11 0xb7ea1c99 in dcpp::NmdcHub::on(dcpp::BufferedSocketListener::X<2>, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#12 0xb7e22c2b in dcpp::BufferedSocket::threadRead() () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#13 0xb7e23320 in dcpp::BufferedSocket::checkSocket() () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#14 0xb7e24c05 in dcpp::BufferedSocket::run() () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#15 0xb7eccf3f in dcpp::Thread::starter(void*) () from /usr/lib/libeiskaltdcpp.so.2.2
No symbol table info available.
\#16 0x45237c77 in start_thread () from /lib/libpthread.so.0
No symbol table info available.
\#17 0x45198c6e in clone () from /lib/libc.so.6
No symbol table info available.

**Comment by dhamp** [comment]
_From [unikum...@gmail.com](https://code.google.com/u/114963251942515168095/) on May 02, 2011 08:14:08_

Записал в лог, думаю, так будет удобнее.

**Attachment:** [backtrace.log](http://code.google.com/p/eiskaltdc/issues/detail?id=1063#hc7)

**Comment by dhamp** [comment]
_From [vasily.n.k@eml.ru](https://code.google.com/u/vasily.n.k@eml.ru/) on May 02, 2011 09:53:03_

Да кстати сколько клиент работает до сбоя?
И сколько жрет памяти? ( посмотреть можно в htop )

Может это банальная утечка памяти себя проявляет и этот баг суть
дубликат https://code.google.com/p/eiskaltdc/issues/detail?id=1027

**Comment by dhamp** [comment]
_From [unikum...@gmail.com](https://code.google.com/u/114963251942515168095/) on May 02, 2011 10:06:10_

Утечка тоже была, не так давно.
В описанной мной ситуации клиент работает несколько минут. По-прежнему считаю, что это каким-то ообразом связано с большим количеством соединений.
