### ISSUE TITLE
Crash when downloading files in queue

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#226]
_From [thereale...@gmail.com](https://code.google.com/u/103290379155803097278/) on July 04, 2012 11:53:40_

What version of the product are you using? On what operating system? What steps will reproduce the problem? 1. add files to queue
2. wait
3. crash What is the expected output? What do you see instead? expected output is for eiskalt to download
the files. 

What I get:

Program received signal SIGSEGV, Segmentation fault.
0x08145ec9 in DownloadQueueItem::row() const ()
(gdb) bt
\#0  0x08145ec9 in DownloadQueueItem::row() const ()
\#1  0x0814601a in DownloadQueueModel::parent(QModelIndex const&) const ()
\#2  0xb724a541 in QAbstractItemModelPrivate::rowsAboutToBeRemoved(QModelIndex const&, int, int) () from /usr/lib/qt4/libQtCore.so.4
\#3  0xb724bf48 in QAbstractItemModel::beginRemoveRows(QModelIndex const&, int, int) () from /usr/lib/qt4/libQtCore.so.4
\#4  0x0814b61d in DownloadQueueModel::remItem(QMap<QString, QVariant> const&) ()
\#5  0x0816c501 in DownloadQueue::remFile(QMap<QString, QVariant> const&) ()
\#6  0x080f65ec in ?? ()
\#7  0xb72675bb in QMetaCallEvent::placeMetaCall(QObject*) () from /usr/lib/qt4/libQtCore.so.4
\#8  0xb726becb in QObject::event(QEvent*) () from /usr/lib/qt4/libQtCore.so.4
\#9  0xb7676894 in QWidget::event(QEvent*) () from /usr/lib/qt4/libQtGui.so.4
\#10 0xb761ba2c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/qt4/libQtGui.so.4
\#11 0xb7620aad in QApplication::notify(QObject*, QEvent*) () from /usr/lib/qt4/libQtGui.so.4
\#12 0xb72555b5 in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/qt4/libQtCore.so.4
\#13 0xb72592e7 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/qt4/libQtCore.so.4
\#14 0xb725950c in QCoreApplication::sendPostedEvents(QObject*, int) () from /usr/lib/qt4/libQtCore.so.4
\#15 0xb72886ee in ?? () from /usr/lib/qt4/libQtCore.so.4
\#16 0xb6b155cd in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
\#17 0x084fb838 in ?? ()
Backtrace stopped: previous frame inner to this frame (corrupt stack?)

It happens "sometimes", now has happened over
5 times in the last hour or so... got annoying. Please provide any additional information below: 1. Qt version 4.8.2 2. libc version 2.15

I tried searching but couldn't find this reported,
if it's reported already, ignore.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1357_

**Comment by dhamp** [comment]
_From [thereale...@gmail.com](https://code.google.com/u/103290379155803097278/) on July 04, 2012 00:57:26_

ofc I forgot the important stuff:
eiskalt: 2.2.7
operating system: linux
