### ISSUE TITLE
Crash when opening user list in eiskaltdcpp-gtk

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#228]
_From [lars...@odus.se](https://code.google.com/u/116520204527460964299/) on July 28, 2012 00:18:58_

What version of the product are you using? EiskaltDC++ version: 2.2.7 (stable)
GTK+ version: 2.24.11
Glib version: 2.32.4 On what operating system? Arch Linux What steps will reproduce the problem? 1. Open gtk interface. 
2. Search for something, and browse some users filelist
3. Only crash on some user. What is the expected output? What do you see instead? When tab should be opened with user filelist, eiskaltdcpp-gtk craches. 

Backtrace attached.

**Attachment:** [crash-eiskaltdcpp-gtk.txt](http://code.google.com/p/eiskaltdc/issues/detail?id=1359)

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1359_

**Comment by dhamp** [comment]
_From [tehnic...@yandex.ru](https://code.google.com/u/102614106087232079264/) on July 04, 2013 07:01:48_

Your current backtrace is useless. Please follow instructions from: https://code.google.com/p/eiskaltdc/wiki/issue_hints_en

**Comment by dhamp** [comment]
_From [markus.l...@gmail.com](https://code.google.com/u/102176934983476662849/) on July 25, 2013 11:55:28_

Ubuntu 13.04

Crash on filelist load-open


...

Gdk:ERROR:/build/buildd/gtk+2.0-2.24.17/gdk/gdkregion-generic.c:1110:miUnionNonO: assertion failed: (y1 \< y2)

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffe9993700 (LWP 4875)]
0x00007ffff5f80037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt full
\#0  0x00007ffff5f80037 in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
\#1  0x00007ffff5f83698 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
\#2  0x00007ffff7b493b6 in g_assertion_message () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#3  0x00007ffff7b49914 in g_assertion_message_expr () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#4  0x00007ffff73ef411 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
No symbol table info available.
\#5  0x00007ffff73f0349 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
No symbol table info available.
\#6  0x00007ffff73f0a27 in gdk_region_union () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
No symbol table info available.
\#7  0x00007ffff73fa687 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
No symbol table info available.
\#8  0x00007ffff6fd4590 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
\#9  0x00007ffff6fd9b5b in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
\#10 0x00007ffff6fd9be8 in gtk_widget_queue_resize ()
   from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
\#11 0x00007ffff6eab8ac in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
\#12 0x00007ffff6eac79d in gtk_label_set_text () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
No symbol table info available.
\#13 0x00000000004a5096 in MainWindow::setStats_gui (this=0x7c97f20, hubs=..., downloadSpeed=..., 
    downloaded=..., uploadSpeed=..., uploaded=...)
    at /build/buildd/eiskaltdcpp-unstable-2.3.0-20130718-020402-cef983c/eiskaltdcpp-gtk/src/mainwindow.cc:775
No locals.
\#14 0x00000000004bc7dd in Func5<MainWindow, std::string, std::string, std::string, std::string, std::string>::call (this=0x7fffb0000e90)
    at /build/buildd/eiskaltdcpp-unstable-2.3.0-20130718-020402-cef983c/eiskaltdcpp-gtk/src/func.hh:191
No locals.
\#15 0x00000000005264ae in WulforManager::processGuiQueue (this=0x7cbd9e0)
    at /build/buildd/eiskaltdcpp-unstable-2.3.0-20130718-020402-cef983c/eiskaltdcpp-gtk/src/wulformanager.cc:264
        func = 0x7fffb0000e90
\#16 0x0000000000526529 in WulforManager::threadFunc_gui (data=<optimized out>)
    at /build/buildd/eiskaltdcpp-unstable-2.3.0-20130718-020402-cef983c/eiskaltdcpp-gtk/src/wulformanager.cc:231
        man = \<optimized out>
\#17 0x00007ffff7b4aeb5 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#18 0x00007ffff6318f8e in start_thread () from /lib/x86_64-linux-gnu/libpthread.so.0
No symbol table info available.
\#19 0x00007ffff6042e1d in clone () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
(gdb)
