### ISSUE TITLE
crashes frequently

### ISSUE THREAD

**Issue by dhamp** [eiskaltdcpp/eiskaltdcpp#239]
_From [pahni...@gmail.com](https://code.google.com/u/107706745019237830500/) on November 18, 2012 19:41:55_

What version of the product are you using? 2.2.7 (stable) On what operating system? Ubuntu 12.10 What steps will reproduce the problem? 1. crashes while loading large file list
2. crashes while opening search/download que/ some other tabs many times What is the expected output? What do you see instead? application exits suddenly while opening large file list/ search tab/ any other tab.
I thinks eiskaltdc can't handle more than 5 tabs. This happens sometimes and sometimes doesn't. But crashes happen very frequently at least 1 time in 20 mins, only while opening new tabs. Please provide any additional information below: 1. Qt version I use gtk version 2. libc version 3. If program crashed, please, provide backtrace (how to provide backtrace you can see at https://code.google.com/p/eiskaltdc/wiki/issue_hints_en ) if started in debugging mode, application won't crash but hangs and stops to respond, even cursor won't change.

bt full when application hangs in gdb mode
\#0  0x00007ffff6bdcc69 in gtk_radio_menu_item_set_group ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#1  0x00007ffff6bdcd80 in gtk_radio_menu_item_new ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#2  0x00007ffff6bdcdae in gtk_radio_menu_item_new_with_label ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#3  0x00000000004fdd9d in BookEntry::BookEntry (this=0x145d410, 
    type=Entry::SEARCH, text=..., ui=..., id=...)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/bookentry.cc:79
        image = 0x1a83ea0
\#4  0x000000000047fe0f in Search::Search (this=0x145d410)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/search.cc:41
No locals.
\#5  0x000000000049ea30 in MainWindow::addSearch_gui (this=this@entry=0xe757d0)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/mainwindow.cc:1011
        entry = \<optimized out>
        t = \<optimized out>
\#6  0x000000000049f858 in MainWindow::actionMagnet_gui (this=0xe757d0, 
    magnet=...)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/mainwindow.cc:1064
---Type \<return> to continue, or q \<return> to quit---
        s = \<optimized out>
        action = 0
        name = {static npos = \<optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, \<No data fields>}, _M_p = 0x1bc7018 "s1.png"}}
        tth = {static npos = \<optimized out>, 
          _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, \<No data fields>}, 
            _M_p = 0x1652a28 "MHNWX4QGFQNFZVWLZABUSWJCKPG4F7LEI5FLLJY"}}
        size = \<optimized out>
        split = \<optimized out>
\#7  0x00000000005334c4 in Hub::onMagnetTagEvent_gui (tag=<optimized out>, 
    textView=<optimized out>, event=<optimized out>, iter=<optimized out>, 
    data=0x7fffd8001900)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/hub.cc:1704
        hub = \<optimized out>
\#8  0x00007ffff6b915dd in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#9  0x00007ffff756a140 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#10 0x00007ffff757b550 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
---Type \<return> to continue, or q \<return> to quit---
No symbol table info available.
\#11 0x00007ffff75830cb in g_signal_emit_valist ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#12 0x00007ffff7583642 in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#13 0x00007ffff6c4fca1 in gtk_text_tag_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#14 0x00007ffff6c52ca9 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#15 0x00007ffff6c57706 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#16 0x00007ffff6b8f99c in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#17 0x00007ffff756a140 in g_closure_invoke ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#18 0x00007ffff757b2d0 in ?? ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#19 0x00007ffff75830cb in g_signal_emit_valist ()
---Type \<return> to continue, or q \<return> to quit---
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#20 0x00007ffff7583642 in g_signal_emit ()
   from /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
No symbol table info available.
\#21 0x00007ffff6cbeb4a in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#22 0x00007ffff6b8d955 in ?? () from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#23 0x00007ffff6b8f653 in gtk_main_do_event ()
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#24 0x00007ffff71047d2 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0
No symbol table info available.
\#25 0x00007ffff77f0ab5 in g_main_context_dispatch ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#26 0x00007ffff77f0de8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#27 0x00007ffff77f11e2 in g_main_loop_run ()
   from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
\#28 0x00007ffff6b8e9b5 in gtk_main ()
---Type \<return> to continue, or q \<return> to quit---
   from /usr/lib/x86_64-linux-gnu/libgtk-3.so.0
No symbol table info available.
\#29 0x0000000000461bce in main (argc=1, argv=0x7fffffffe298)
    at /build/buildd/eiskaltdcpp-2.2.7/eiskaltdcpp-gtk/src/wulfor.cc:180
No locals.

_Original issue: http://code.google.com/p/eiskaltdc/issues/detail?id=1380_

**Comment by dhamp** [comment]
_From [pahni...@gmail.com](https://code.google.com/u/107706745019237830500/) on November 18, 2012 07:42:46_

Same crashing also happened when I was using fedora 17, more frequently
