### ISSUE TITLE
crash filelistloader

### ISSUE THREAD

**Issue by axet** [eiskaltdcpp/eiskaltdcpp#486]
eiskaltdcpp-gtk

2.4.2-1+b2

debian / bookworm

```
Thread 66 "filelistloader" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb1ffb640 (LWP 1181195)]
0x00007ffff782ea6a in gtk_widget_style_get_valist (widget=0x7fffe866a7b0 [GtkTreeView], first_property_name=<optimized out>, var_args=0x7fffb1ffa1a0) at ../../../../gtk/gtkwidget.c:13339
13339	../../../../gtk/gtkwidget.c: No such file or directory.
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007ffff782ea6a in gtk_widget_style_get_valist (widget=0x7fffe866a7b0 [GtkTreeView], first_property_name=<optimized out>, var_args=0x7fffb1ffa1a0)
    at ../../../../gtk/gtkwidget.c:13339
#1  0x00007ffff782edda in gtk_widget_style_get
    (widget=widget@entry=0x7fffe866a7b0 [GtkTreeView], first_property_name=first_property_name@entry=0x7ffff7883891 "expander-size")
    at ../../../../gtk/gtkwidget.c:13373
#2  0x00007ffff77fbe9a in gtk_tree_view_get_expander_size (tree_view=0x7fffe866a7b0 [GtkTreeView]) at ../../../../gtk/gtktreeview.c:3127
#3  gtk_tree_view_get_row_height (node=0x7fffe402d4d0, tree_view=0x7fffe866a7b0 [GtkTreeView]) at ../../../../gtk/gtktreeview.c:13804
#4  _gtk_tree_view_queue_draw_node
    (tree_view=tree_view@entry=0x7fffe866a7b0 [GtkTreeView], tree=tree@entry=0x7fffa4acd710, node=node@entry=0x7fffe402d4d0, clip_rect=clip_rect@entry=0x0)
    at ../../../../gtk/gtktreeview.c:10184
#5  0x00007ffff7800cb7 in _gtk_tree_view_queue_draw_node (clip_rect=0x0, node=0x7fffe402d4d0, tree=0x7fffa4acd710, tree_view=0x7fffe866a7b0 [GtkTreeView])
    at ../../../../gtk/gtktreeview.c:10176
#6  gtk_tree_view_row_has_child_toggled
    (model=model@entry=0x7fffe87632c0, path=path@entry=0x7fffe863fd60, iter=iter@entry=0x0, data=data@entry=0x7fffe866a7b0)
    at ../../../../gtk/gtktreeview.c:9252
#7  0x00007ffff7801094 in gtk_tree_view_row_inserted (model=0x7fffe87632c0, path=0x7fffe80edb00, iter=<optimized out>, data=0x7fffe866a7b0)
    at ../../../../gtk/gtktreeview.c:9134
#11 0x00007ffff7e306bf in <emit signal ??? on instance 0x7fffe87632c0 [GtkTreeStore]>
    (instance=instance@entry=0x7fffe87632c0, signal_id=<optimized out>, detail=detail@entry=0) at ../../../gobject/gsignal.c:3553
    #8  0x00007ffff7e1771f in g_closure_invoke
    (closure=0x7fffe8767910, return_value=return_value@entry=0x0, n_param_values=3, param_values=param_values@entry=0x7fffb1ffa580, invocation_hint=invocation_hint@entry=0x7fffb1ffa500) at ../../../gobject/gclosure.c:830
    #9  0x00007ffff7e29cf6 in signal_emit_unlocked_R
    (node=node@entry=0x555555c99390, detail=detail@entry=0, instance=instance@entry=0x7fffe87632c0, emission_return=emission_return@entry=0x0, instance_and_params=instance_and_params@entry=0x7fffb1ffa580) at ../../../gobject/gsignal.c:3743
    #10 0x00007ffff7e30111 in g_signal_emit_valist
    (instance=<optimized out>, signal_id=<optimized out>, detail=<optimized out>, var_args=var_args@entry=0x7fffb1ffa730) at ../../../gobject/gsignal.c:3496
#12 0x00007ffff77e5dba in gtk_tree_model_row_inserted
    (tree_model=tree_model@entry=0x7fffe87632c0, path=path@entry=0x7fffe80edb00, iter=iter@entry=0x7fffb1ffa880) at ../../../../gtk/gtktreemodel.c:1867
#13 0x00007ffff77f802b in gtk_tree_store_append (tree_store=0x7fffe87632c0 [GtkTreeStore], iter=0x7fffb1ffa880, parent=0x7fffb1ffa960)
    at ../../../../gtk/gtktreestore.c:1759
#14 0x00005555556d604a in ShareBrowser::buildDirs_gui(dcpp::DirectoryListing::Directory*, _GtkTreeIter*)
     (this=0x7fffe86290d0, dir=0x7fff8a07af38, iter=<optimized out>) at ./eiskaltdcpp-gtk/src/sharebrowser.cc:277
#15 0x00005555556d623d in ShareBrowser::buildDirs_gui(dcpp::DirectoryListing::Directory*, _GtkTreeIter*)
    (this=0x7fffe86290d0, dir=0x7fff8a07aea0, iter=<optimized out>) at ./eiskaltdcpp-gtk/src/sharebrowser.cc:293
#16 0x00005555556dc245 in ShareBrowser::buildList_gui() (this=0x7fffe86290d0) at ./dcpp/DirectoryListing.h:147
#17 0x00005555556dc39a in ShareBrowser::threadLoad_list(void*) (data=0x7fffe86290d0) at ./eiskaltdcpp-gtk/src/sharebrowser.cc:187
#18 0x00007ffff7ede59d in g_thread_proxy (data=0x7fffe8705b00) at ../../../glib/gthread.c:827
--Type <RET> for more, q to quit, c to continue without paging--c
#19 0x00007ffff71dbd80 in start_thread (arg=0x7fffb1ffb640) at pthread_create.c:481
#20 0x00007ffff6fb2baf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb) 
```

**Comment by axet** [comment]
can be duplicate of #229
